version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/marsops
    depends_on:
      - mongodb
    networks:
      - marsops-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - marsops-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - marsops-network

volumes:
  mongodb_data:

networks:
  marsops-network:
    driver: bridge 